# Imersão de Pandas - Teo Me Why

### Breve revisão de Python - Turbo

In [1]:
#cd /home/juliana-duque/anaconda3/bin
#anaconda-navigator
#environment -> base(root) -> open with jupyter notebook

#### Strings

In [2]:
nome = "Téo Calvo"
print(nome)

Téo Calvo

In [3]:
nome.upper()

'TÉO CALVO'

In [4]:
nome.lower()

'téo calvo'

In [5]:
nome[:3]

'Téo'

In [6]:
nome[::-1] # -> start; stop; step

'ovlaC oéT'

In [7]:
nome[::2]

'ToClo'

#### Numéricos

In [8]:
type(1)

int

In [9]:
type(1.)

float

In [10]:
type(True)

bool

In [11]:
print(1 + 1. + True) # soma
print(2 ** 3)        # potência
print(3 * 2)         # muiltiplicação
print(3 / 2)         # divisão
print( 3 % 2)        # resto da divisão
print( 3 // 2)       # divisão inteira

3.0
8
6
1.5
1
1

#### Listas
* list comprehension

In [12]:
minha_lista = ["Téo", 28, ["Maria", "Jozefina", "Natalia"], True ]

In [13]:
len(minha_lista) # Quantidade de elementos na lista

4

In [14]:
minha_lista[-1]

True

In [15]:
minha_lista[2][0]

'Maria'

In [16]:
minha_lista[0] # Primeiro elemento

'Téo'

In [17]:
minha_lista[2][::-1]

['Natalia', 'Jozefina', 'Maria']

#### Dicionários

In [18]:
dados = { "nome":["Téo", "Nah", "Lara"],
          "sobrenome":["Calvo", "Gironde", "Calvo"],
          "idade":[28,30,27]
        }

In [19]:
dados["nome"][0]

'Téo'

In [20]:
dados["genero"] = ["M", "F", "F"]

In [21]:
dados["nome"][0].lower()

'téo'

#### If, Else, Elif

In [22]:
idade = input( "Entre com a sua idade" )
idade = int(idade)

if idade < 18:
    print("Beba leite que é para sua idade")
    
elif idade <= 65:
    print("Beba a vontade, mas sem dirigir")
    
else:
    print("Cuidado, pois sua idade é avançada")

Entre com a sua idade18
Beba a vontade, mas sem dirigir

#### For & While

In [23]:
for i in range(1,11):
    if i % 2 == 0:
        print(i, "é par")
    else:
        print(i, "é impar")

1 é impar
2 é par
3 é impar
4 é par
5 é impar
6 é par
7 é impar
8 é par
9 é impar
10 é par

In [24]:
i = 1
while True:
    print(i)
    if i == 10:
        break
    i += 1

1
2
3
4
5
6
7
8
9
10

In [25]:
i = 1
while i <= 10:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10

#### Funções

In [26]:
def calc_cubo(x):
    return x ** 3

In [27]:
calc_cubo(4)

64

In [28]:
def funcao_bivariada(x, y):
    return 2 * x + 4 * (y ** 3)

In [29]:
funcao_bivariada(10, 4)

276

## Finalmente, Pandas


Fingindo um pouco a análise de dados

### Comandos básicos

* Importação da biblioteca
* O que são Series e Dataframes?
    - Criando o primeiro dataframe
* Leitura de arquivos
* Escrita de arquivos
* Operações básicas de DataFrame

In [30]:
import pandas as pd # Importa a biblica Pandas com o alias (apelido) pd

 ### Séries

In [31]:
minha_serie = pd.Series(["Téo", "Nah", "Lara", "Ju"])
minha_serie

0     Téo
1     Nah
2    Lara
3      Ju
dtype: object

In [32]:
minha_serie[1:]

1     Nah
2    Lara
3      Ju
dtype: object

In [33]:
minha_serie.name

In [34]:
dados = {"nome": ["Teo", "Nah", "Lara", "Ju"]}
nova_serie = pd.Series(dados, name = "nome")

In [35]:
nova_serie == "Téo"

nome    False
Name: nome, dtype: bool

In [36]:
idade = pd.Series( [43, 24 ,27 ,10, 15, 17, 30, 45 ])
idade

0    43
1    24
2    27
3    10
4    15
5    17
6    30
7    45
dtype: int64

In [37]:
idade > 18

0     True
1     True
2     True
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [38]:
idade * 10

0    430
1    240
2    270
3    100
4    150
5    170
6    300
7    450
dtype: int64

### Testando

In [39]:
dados = { "nome":["Téo", "Nah", "Lara", "Ju"],
         "sobrenome":["Calvo", "Gironde", "Calvo", "Duc"],
         "idade":[28,30,27, 26], }

In [40]:
dados

{'nome': ['Téo', 'Nah', 'Lara', 'Ju'],
 'sobrenome': ['Calvo', 'Gironde', 'Calvo', 'Duc'],
 'idade': [28, 30, 27, 26]}

In [41]:
dados["nome"] # retorna lista

['Téo', 'Nah', 'Lara', 'Ju']

In [42]:
df_dados = pd.DataFrame(dados)

In [43]:
df_dados["nome"] # retorna uma serie

0     Téo
1     Nah
2    Lara
3      Ju
Name: nome, dtype: object

In [44]:
df_dados["nome"].tolist() #converte para lista

['Téo', 'Nah', 'Lara', 'Ju']

In [45]:
df_dados["nome"] == "Téo"

0     True
1    False
2    False
3    False
Name: nome, dtype: bool

In [46]:
df_dados

   nome sobrenome  idade
0   Téo     Calvo     28
1   Nah   Gironde     30
2  Lara     Calvo     27
3    Ju       Duc     26

### Importando dados

In [47]:
df_votacao = pd.read_csv("../data/votacao_agg_estado.csv")

/home/teo/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [48]:
df_votacao

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,0,0,0,0,0,181257
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,0,0,0,0,0,22623
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,0,0,0,0,0,3362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511100,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,GOVERNADOR,APTO,NaN,MARCOS JOSE ROCHA DOS SANTOS,...,0,0,0,0,0,0,0,0,0,530188
511101,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,ANTONIO CARLOS VALADARES FILHO,...,0,0,0,0,0,0,0,0,0,370161
511102,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,JOAO ALBERTO RODRIGUES CAPIBERIBE,...,0,0,0,0,0,0,0,0,0,174540
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

In [49]:
df_votacao.head(2) # mostra as duas primeiras linhas do dataframe

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680

In [50]:
df_votacao.tail(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
511103,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,MARCIO LUIZ FRANCA GOMES,...,0,0,0,0,0,0,0,0,0,20497480
511104,2018,ELEICOES GERAIS ESTADUAIS 2018,2,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,APTO,NaN,RODRIGO SOBRAL ROLLEMBERG,...,0,0,0,0,0,451329,0,0,0,451329

In [51]:
# Dimensoes do dataframe
df_votacao.shape

(511105, 43)

In [52]:
# Quais são suas colunas?
df_votacao.columns

Index(['ano_eleicao', 'descricao_eleicao', 'numero_turno', 'nome_partido',
       'numero_partido', 'sigla_partido', 'descricao_cargo',
       'descricao_situacao_candidatura',
       'descricao_situacao_candidatura_superior', 'nome', 'nome_social',
       'nome_urna', 'numero_sequencial', 'numero_urna', 'total_votos_ac',
       'total_votos_al', 'total_votos_am', 'total_votos_ap', 'total_votos_ba',
       'total_votos_rj', 'total_votos_sp', 'total_votos_ce', 'total_votos_ro',
       'total_votos_se', 'total_votos_pr', 'total_votos_mg', 'total_votos_mt',
       'total_votos_pe', 'total_votos_pb', 'total_votos_zz', 'total_votos_go',
       'total_votos_rs', 'total_votos_rn', 'total_votos_to', 'total_votos_pa',
       'total_votos_ms', 'total_votos_pi', 'total_votos_ma', 'total_votos_df',
       'total_votos_es', 'total_votos_rr', 'total_votos_sc', 'total_votos'],
      dtype='object')

In [53]:
# Quais são suas colunas?
df_votacao.columns.tolist()

['ano_eleicao',
 'descricao_eleicao',
 'numero_turno',
 'nome_partido',
 'numero_partido',
 'sigla_partido',
 'descricao_cargo',
 'descricao_situacao_candidatura',
 'descricao_situacao_candidatura_superior',
 'nome',
 'nome_social',
 'nome_urna',
 'numero_sequencial',
 'numero_urna',
 'total_votos_ac',
 'total_votos_al',
 'total_votos_am',
 'total_votos_ap',
 'total_votos_ba',
 'total_votos_rj',
 'total_votos_sp',
 'total_votos_ce',
 'total_votos_ro',
 'total_votos_se',
 'total_votos_pr',
 'total_votos_mg',
 'total_votos_mt',
 'total_votos_pe',
 'total_votos_pb',
 'total_votos_zz',
 'total_votos_go',
 'total_votos_rs',
 'total_votos_rn',
 'total_votos_to',
 'total_votos_pa',
 'total_votos_ms',
 'total_votos_pi',
 'total_votos_ma',
 'total_votos_df',
 'total_votos_es',
 'total_votos_rr',
 'total_votos_sc',
 'total_votos']

In [54]:
type(df_votacao.columns.tolist())

list

In [55]:
df_votacao.index

RangeIndex(start=0, stop=511105, step=1)

## Utilitários

In [56]:
df_votacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 511105 entries, 0 to 511104
Data columns (total 43 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   ano_eleicao                              511105 non-null  int64
 1   descricao_eleicao                        511105 non-null  object
 2   numero_turno                             511105 non-null  int64
 3   nome_partido                             511105 non-null  object
 4   numero_partido                           511105 non-null  int64
 5   sigla_partido                            511105 non-null  object
 6   descricao_cargo                          511105 non-null  object
 7   descricao_situacao_candidatura           511105 non-null  object
 8   descricao_situacao_candidatura_superior  484655 non-null  object
 9   nome                                     511105 non-null  object
 10  nome_social                              0 non-null       float64
 11  nome_urna                                511095 non-null  object
 12  numero_sequencial                        511105 non-null  int64
 13  numero_urna                              511105 non-null  int64
 14  total_votos_ac                           511105 non-null  int64
 15  total_votos_al                           511105 non-null  int64
 16  total_votos_am                           511105 non-null  int64
 17  total_votos_ap                           511105 non-null  int64
 18  total_votos_ba                           511105 non-null  int64
 19  total_votos_rj                           511105 non-null  int64
 20  total_votos_sp                           511105 non-null  int64
 21  total_votos_ce                           511105 non-null  int64
 22  total_votos_ro                           511105 non-null  int64
 23  total_votos_se                           511105 non-null  int64
 24  total_votos_pr                           511105 non-null  int64
 25  total_votos_mg                           511105 non-null  int64
 26  total_votos_mt                           511105 non-null  int64
 27  total_votos_pe                           511105 non-null  int64
 28  total_votos_pb                           511105 non-null  int64
 29  total_votos_zz                           511105 non-null  int64
 30  total_votos_go                           511105 non-null  int64
 31  total_votos_rs                           511105 non-null  int64
 32  total_votos_rn                           511105 non-null  int64
 33  total_votos_to                           511105 non-null  int64
 34  total_votos_pa                           511105 non-null  int64
 35  total_votos_ms                           511105 non-null  int64
 36  total_votos_pi                           511105 non-null  int64
 37  total_votos_ma                           511105 non-null  int64
 38  total_votos_df                           511105 non-null  int64
 39  total_votos_es                           511105 non-null  int64
 40  total_votos_rr                           511105 non-null  int64
 41  total_votos_sc                           511105 non-null  int64
 42  total_votos                              511105 non-null  int64
dtypes: float64(1), int64(34), object(8)
memory usage: 167.7+ MB

In [57]:
df_votacao.dtypes

ano_eleicao                                  int64
descricao_eleicao                           object
numero_turno                                 int64
nome_partido                                object
numero_partido                               int64
sigla_partido                               object
descricao_cargo                             object
descricao_situacao_candidatura              object
descricao_situacao_candidatura_superior     object
nome                                        object
nome_social                                float64
nome_urna                                   object
numero_sequencial                            int64
numero_urna                                  int64
total_votos_ac                               int64
total_votos_al                               int64
total_votos_am                               int64
total_votos_ap                               int64
total_votos_ba                               int64
total_votos_rj                               int64
total_votos_sp                               int64
total_votos_ce                               int64
total_votos_ro                               int64
total_votos_se                               int64
total_votos_pr                               int64
total_votos_mg                               int64
total_votos_mt                               int64
total_votos_pe                               int64
total_votos_pb                               int64
total_votos_zz                               int64
total_votos_go                               int64
total_votos_rs                               int64
total_votos_rn                               int64
total_votos_to                               int64
total_votos_pa                               int64
total_votos_ms                               int64
total_votos_pi                               int64
total_votos_ma                               int64
total_votos_df                               int64
total_votos_es                               int64
total_votos_rr                               int64
total_votos_sc                               int64
total_votos                                  int64
dtype: object

In [58]:
df_votacao.dtypes.index

Index(['ano_eleicao', 'descricao_eleicao', 'numero_turno', 'nome_partido',
       'numero_partido', 'sigla_partido', 'descricao_cargo',
       'descricao_situacao_candidatura',
       'descricao_situacao_candidatura_superior', 'nome', 'nome_social',
       'nome_urna', 'numero_sequencial', 'numero_urna', 'total_votos_ac',
       'total_votos_al', 'total_votos_am', 'total_votos_ap', 'total_votos_ba',
       'total_votos_rj', 'total_votos_sp', 'total_votos_ce', 'total_votos_ro',
       'total_votos_se', 'total_votos_pr', 'total_votos_mg', 'total_votos_mt',
       'total_votos_pe', 'total_votos_pb', 'total_votos_zz', 'total_votos_go',
       'total_votos_rs', 'total_votos_rn', 'total_votos_to', 'total_votos_pa',
       'total_votos_ms', 'total_votos_pi', 'total_votos_ma', 'total_votos_df',
       'total_votos_es', 'total_votos_rr', 'total_votos_sc', 'total_votos'],
      dtype='object')

In [59]:
df_votacao.dtypes["ano_eleicao"]

dtype('int64')

## Navegação pelo DataFrame

# Sintaxe geral
df[coluna][linha]

In [60]:
type(df_votacao["nome"][511100])

str

In [61]:
df_votacao["nome"][511100] #coluna, indice

'MARCOS JOSE ROCHA DOS SANTOS'

In [62]:
df_votacao["nome"]

0                   AMAZONINO ARMANDO MENDES
1              CARLOS EDUARDO DE SOUZA BRAGA
2                      JOSE RICARDO WENDLING
3         MAURICIO WILKER DE AZEVEDO BARRETO
4               JADELVONE NOGUEIRA DELTRUDES
                         ...
511100          MARCOS JOSE ROCHA DOS SANTOS
511101        ANTONIO CARLOS VALADARES FILHO
511102     JOAO ALBERTO RODRIGUES CAPIBERIBE
511103              MARCIO LUIZ FRANCA GOMES
511104             RODRIGO SOBRAL ROLLEMBERG
Name: nome, Length: 511105, dtype: object

In [63]:
df_votacao["nome"] == 'MARCOS JOSE ROCHA DOS SANTOS'

0         False
1         False
2         False
3         False
4         False
          ...
511100     True
511101    False
511102    False
511103    False
511104    False
Name: nome, Length: 511105, dtype: bool

In [64]:
# lista todas as colunas
df_votacao.columns.tolist()

['ano_eleicao',
 'descricao_eleicao',
 'numero_turno',
 'nome_partido',
 'numero_partido',
 'sigla_partido',
 'descricao_cargo',
 'descricao_situacao_candidatura',
 'descricao_situacao_candidatura_superior',
 'nome',
 'nome_social',
 'nome_urna',
 'numero_sequencial',
 'numero_urna',
 'total_votos_ac',
 'total_votos_al',
 'total_votos_am',
 'total_votos_ap',
 'total_votos_ba',
 'total_votos_rj',
 'total_votos_sp',
 'total_votos_ce',
 'total_votos_ro',
 'total_votos_se',
 'total_votos_pr',
 'total_votos_mg',
 'total_votos_mt',
 'total_votos_pe',
 'total_votos_pb',
 'total_votos_zz',
 'total_votos_go',
 'total_votos_rs',
 'total_votos_rn',
 'total_votos_to',
 'total_votos_pa',
 'total_votos_ms',
 'total_votos_pi',
 'total_votos_ma',
 'total_votos_df',
 'total_votos_es',
 'total_votos_rr',
 'total_votos_sc',
 'total_votos']

In [65]:
df_votacao["sigla_partido"][4] #navegando em colunas

'PPL'

In [66]:
df_votacao.iloc[0]

ano_eleicao                                                             2014
descricao_eleicao                          ELEICAO SUPLEMENTAR GOVERNADOR AM
numero_turno                                                               1
nome_partido                                 PARTIDO DEMOCRATICO TRABALHISTA
numero_partido                                                            12
sigla_partido                                                            PDT
descricao_cargo                                                   GOVERNADOR
descricao_situacao_candidatura                                      DEFERIDO
descricao_situacao_candidatura_superior                                 APTO
nome                                                AMAZONINO ARMANDO MENDES
nome_social                                                              NaN
nome_urna                                                   AMAZONINO MENDES
numero_sequencial                                                40000012067
numero_urna                                                               12
total_votos_ac                                                             0
total_votos_al                                                             0
total_votos_am                                                        577397
total_votos_ap                                                             0
total_votos_ba                                                             0
total_votos_rj                                                             0
total_votos_sp                                                             0
total_votos_ce                                                             0
total_votos_ro                                                             0
total_votos_se                                                             0
total_votos_pr                                                             0
total_votos_mg                                                             0
total_votos_mt                                                             0
total_votos_pe                                                             0
total_votos_pb                                                             0
total_votos_zz                                                             0
total_votos_go                                                             0
total_votos_rs                                                             0
total_votos_rn                                                             0
total_votos_to                                                             0
total_votos_pa                                                             0
total_votos_ms                                                             0
total_votos_pi                                                             0
total_votos_ma                                                             0
total_votos_df                                                             0
total_votos_es                                                             0
total_votos_rr                                                             0
total_votos_sc                                                             0
total_votos                                                           577397
Name: 0, dtype: object

In [67]:
df_votacao.iloc[3] #navegando em indices

ano_eleicao                                                              2014
descricao_eleicao                           ELEICAO SUPLEMENTAR GOVERNADOR AM
numero_turno                                                                1
nome_partido                               PARTIDO HUMANISTA DA SOLIDARIEDADE
numero_partido                                                             31
sigla_partido                                                             PHS
descricao_cargo                                                    GOVERNADOR
descricao_situacao_candidatura                                       DEFERIDO
descricao_situacao_candidatura_superior                                  APTO
nome                                       MAURICIO WILKER DE AZEVEDO BARRETO
nome_social                                                               NaN
nome_urna                                                      WILKER BARRETO
numero_sequencial                                                 40000012061
numero_urna                                                                31
total_votos_ac                                                              0
total_votos_al                                                              0
total_votos_am                                                          22623
total_votos_ap                                                              0
total_votos_ba                                                              0
total_votos_rj                                                              0
total_votos_sp                                                              0
total_votos_ce                                                              0
total_votos_ro                                                              0
total_votos_se                                                              0
total_votos_pr                                                              0
total_votos_mg                                                              0
total_votos_mt                                                              0
total_votos_pe                                                              0
total_votos_pb                                                              0
total_votos_zz                                                              0
total_votos_go                                                              0
total_votos_rs                                                              0
total_votos_rn                                                              0
total_votos_to                                                              0
total_votos_pa                                                              0
total_votos_ms                                                              0
total_votos_pi                                                              0
total_votos_ma                                                              0
total_votos_df                                                              0
total_votos_es                                                              0
total_votos_rr                                                              0
total_votos_sc                                                              0
total_votos                                                             22623
Name: 3, dtype: object

In [68]:
df_votacao.iloc[3]["nome"]

'MAURICIO WILKER DE AZEVEDO BARRETO'

In [69]:
df_votacao["nome"][3]

'MAURICIO WILKER DE AZEVEDO BARRETO'

## Filtros

* Comparações lógicas de ==, >, >=, <, <=, !=
* isna()
* isin()

In [70]:
filtro = [False, True, True, True]
df_dados[filtro]

   nome sobrenome  idade
1   Nah   Gironde     30
2  Lara     Calvo     27
3    Ju       Duc     26

In [71]:
filtro_idade = df_dados["idade"] >= 28 
df_dados[filtro_idade]

  nome sobrenome  idade
0  Téo     Calvo     28
1  Nah   Gironde     30

In [72]:
df_dados[filtro_idade]["idade"]

0    28
1    30
Name: idade, dtype: int64

In [73]:
df_dados[filtro_idade]["nome"]

0    Téo
1    Nah
Name: nome, dtype: object

In [74]:
df_dados[filtro_idade]["nome"].tolist()

['Téo', 'Nah']

In [75]:
df_dados[df_dados["sobrenome"] == "Calvo"]

   nome sobrenome  idade
0   Téo     Calvo     28
2  Lara     Calvo     27

In [76]:
df_calvo = df_dados[df_dados["sobrenome"] == "Calvo"].copy()

In [77]:
df_calvo

   nome sobrenome  idade
0   Téo     Calvo     28
2  Lara     Calvo     27

In [78]:
#ah tá, entendi a pergunta...
# acho que o iloc é mais pra navegar pelos índices ; do dataframe usando os nomes das colunas/indices

In [79]:
df_calvo ["genero"] = ["M", "F"]

In [80]:
df_calvo

   nome sobrenome  idade genero
0   Téo     Calvo     28      M
2  Lara     Calvo     27      F

In [81]:
a = [1,2,3]
#b = a
b = a.copy()

In [82]:
b.append(4)

In [83]:
print(b)

[1, 2, 3, 4]

In [84]:
print(a)

[1, 2, 3]

In [85]:
df_calvo = df_dados[ filtro ]
df_calvo

   nome sobrenome  idade
1   Nah   Gironde     30
2  Lara     Calvo     27
3    Ju       Duc     26

###  Conhecendo Where

In [86]:
filtro_calvo_28 = ( df_dados["sobrenome"] == "Calvo") & (df_dados ["idade"] >= 28)

In [87]:
df_calvo_28 = df_dados[filtro_calvo_28].copy()
df_calvo_28

  nome sobrenome  idade
0  Téo     Calvo     28

In [88]:
df_dados.where(filtro_calvo_28).dropna(how="all")

  nome sobrenome  idade
0  Téo     Calvo   28.0

In [89]:
df_dados.where(filtro_calvo_28).isna()

    nome  sobrenome  idade
0  False      False  False
1   True       True   True
2   True       True   True
3   True       True   True

# Como fica nos políticos?

In [90]:
df_votacao[df_votacao["sigla_partido"] == "PSOL"]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
15634,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,DEPUTADO DISTRITAL,DEFERIDO,APTO,ALEX CARVALHO REGO,...,0,0,0,0,0,332,0,0,0,332
15635,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,DEPUTADO DISTRITAL,DEFERIDO,APTO,ANTONIO ALVES RABELO,...,0,0,0,0,0,156,0,0,0,156
15636,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,DEPUTADO DISTRITAL,DEFERIDO,APTO,ANTONIO FERREIRA DA SILVA,...,0,0,0,0,0,87,0,0,0,87
15637,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,DEPUTADO DISTRITAL,DEFERIDO,APTO,BENEDITO VELOSO DA COSTA,...,0,0,0,0,0,356,0,0,0,356
15638,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,DEPUTADO DISTRITAL,DEFERIDO,APTO,CELSO RIBEIRO PAZ,...,0,0,0,0,0,98,0,0,0,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504384,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SAULO PINTO SILVA,...,0,0,0,0,87100,0,0,0,0,87100
504385,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SILVIA ANDREA FERRARO,...,0,0,0,0,0,0,0,0,0,543583
504386,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SONIA MEIRE SANTOS AZEVEDO DE JESUS,...,0,0,0,0,0,0,0,0,0,62770
504387,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,TELMA GURGEL DA SILVA,...,0,0,0,0,0,0,0,0,0,23846
504388,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,URSULA VIDAL SANTIAGO DE MENDONCA,...,0,585344,0,0,0,0,0,0,0,585344

In [91]:
 filtro_sen_psol = ( 
                     (df_votacao["sigla_partido"] == "PSOL") &
                     (df_votacao["descricao_cargo"] == "SENADOR") &
                     (df_votacao["descricao_situacao_candidatura"] == "APTO")
                     )

df_votacao[filtro_sen_psol]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
504355,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,ALBANISE PIRES FERREIRA DE AZEVEDO,...,0,0,0,0,0,0,0,0,0,142280
504356,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,ANISIO GUILHERME DA FONSECA,...,0,0,28888,0,0,0,0,0,0,28888
504357,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,ANNA KARINA CAVALCANTE DE OLIVEIRA,...,0,0,0,0,0,0,0,0,0,316922
504358,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,ANTONIO VALMOR DE CAMPOS,...,0,0,0,0,0,0,0,0,51191,51191
504359,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,CICERO FERREIRA ALBUQUERQUE,...,0,0,0,0,0,0,0,0,0,57747
504360,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,DANIEL TOJEIRA CARA,...,0,0,0,0,0,0,0,0,0,440118
504361,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,DUDA SALABERT,...,0,0,0,0,0,0,0,0,0,351874
504362,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,FABIO NOGUEIRA DE OLIVEIRA,...,0,0,0,0,0,0,0,0,0,165705
504363,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,FABRICIO SILVA ROSA,...,0,0,0,0,0,0,0,0,0,45833
504364,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,FRANCISCO CLAUDIO CORREA MEYER SANT ANNA,...,0,0,0,0,0,17074,0,0,0,17074
504365,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,FRANCISCO RODRIGUES DE ALENCAR FILHO,...,0,0,0,0,0,0,0,0,0,1281373
504366,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,GILBERTO LOPES FILHO,...,0,0,0,0,0,0,0,0,0,6079
504367,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,JACQUELINE PARMIGIANI,...,0,0,0,0,0,0,0,0,0,77450
504368,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,JAMIESON RODRIGUES SIMOES,...,0,0,0,0,0,0,0,0,0,150644
504369,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,JESUS RODRIGUES ALVES,...,0,0,0,72755,0,0,0,0,0,72755
504370,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,JOSE NIVALDO MANGUEIRA DE ASSIS,...,0,0,0,0,0,0,0,0,0,14461
504371,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,JOSSIMARIO DE SOUZA MICK,...,0,0,0,0,0,0,0,0,0,11650
504372,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,LAILSON DE ALMEIDA,...,0,0,0,0,0,0,0,0,0,7420
504373,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,LIUDIMILA KATRINI PROXIMOZER,...,0,0,0,0,0,0,24496,0,0,24496
504374,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,LUIZ FERNANDO DE SOUZA SANTOS,...,0,0,0,0,0,0,0,0,0,27488
504375,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,MARIA EUGENIA WANDERLEY LIMA,...,0,0,0,0,0,0,0,0,0,113703
504376,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,MARIVALDO DE CASTRO PEREIRA,...,0,0,0,0,0,83112,0,0,0,83112
504377,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,MAURO CESAR LARA DE BARROS,...,0,0,0,0,0,0,0,0,0,226053
504378,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,MELQUESEDEC MAGALHAES AIRES,...,12312,0,0,0,0,0,0,0,0,12312
504379,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,NELSON ALEIXO DA SILVA JUNIOR,...,0,0,0,0,0,0,0,0,0,82153
504380,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,PEDRO CABRAL FILHO,...,0,0,0,0,0,0,0,0,63523,63523
504381,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,RODRIGO TOMAZINI DIAS,...,0,0,0,0,0,0,0,0,0,35233
504382,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,ROMER DOS SANTOS GUEX,...,0,0,0,0,0,0,0,0,0,49023
504383,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,RONDINELY FONSECA DA SILVEIRA,...,0,0,0,0,0,0,0,0,0,14650
504384,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SAULO PINTO SILVA,...,0,0,0,0,87100,0,0,0,0,87100
504385,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SILVIA ANDREA FERRARO,...,0,0,0,0,0,0,0,0,0,543583
504386,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,SONIA MEIRE SANTOS AZEVEDO DE JESUS,...,0,0,0,0,0,0,0,0,0,62770
504387,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,TELMA GURGEL DA SILVA,...,0,0,0,0,0,0,0,0,0,23846
504388,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIALISMO E LIBERDADE,50,PSOL,SENADOR,APTO,NaN,URSULA VIDAL SANTIAGO DE MENDONCA,...,0,585344,0,0,0,0,0,0,0,585344

In [92]:
colunas_interesse  = ["nome", "sigla_partido"]
df_votacao[colunas_interesse]

                                      nome sigla_partido
0                 AMAZONINO ARMANDO MENDES           PDT
1            CARLOS EDUARDO DE SOUZA BRAGA          PMDB
2                    JOSE RICARDO WENDLING            PT
3       MAURICIO WILKER DE AZEVEDO BARRETO           PHS
4             JADELVONE NOGUEIRA DELTRUDES           PPL
...                                    ...           ...
511100        MARCOS JOSE ROCHA DOS SANTOS           PSL
511101      ANTONIO CARLOS VALADARES FILHO           PSB
511102   JOAO ALBERTO RODRIGUES CAPIBERIBE           PSB
511103            MARCIO LUIZ FRANCA GOMES           PSB
511104           RODRIGO SOBRAL ROLLEMBERG           PSB

[511105 rows x 2 columns]

In [93]:
#exemplo de na
import numpy as np

df_tmp = pd.DataFrame( { "nome": ["Téo", "Nah", np.nan],
                         "idade" : [28, 30,31] } )

df_tmp [df_tmp ["nome"].isna()]

  nome  idade
2  NaN     31

## Renomeando Colunas

In [94]:
dados = { "nome":["Téo", "Nah", "Lara", "Ju"],
         "sobrenome":["Calvo", "Gironde", "Calvo", "Duc"],
         "idade":[28,30,27, 26], }
df_dados = pd.DataFrame(dados)

#criando uma coluna nova
df_dados ["Genero"] = ["M", "F", "F", "F"]

In [95]:
df_dados

   nome sobrenome  idade Genero
0   Téo     Calvo     28      M
1   Nah   Gironde     30      F
2  Lara     Calvo     27      F
3    Ju       Duc     26      F

In [96]:
#executar um comando apenas
df_dados = df_dados.rename(columns={"Genero":"genero"}, inplace=False) #atribui ao dataframe, true atribui

#df_dados.rename(columns={"Genero":"genero"}, inplace=False) #atribui ao dataframe, true atribui

In [97]:
df_dados

   nome sobrenome  idade genero
0   Téo     Calvo     28      M
1   Nah   Gironde     30      F
2  Lara     Calvo     27      F
3    Ju       Duc     26      F

In [98]:
df_dados["colunaErro"] = False

In [99]:
df_dados

   nome sobrenome  idade genero  colunaErro
0   Téo     Calvo     28      M       False
1   Nah   Gironde     30      F       False
2  Lara     Calvo     27      F       False
3    Ju       Duc     26      F       False

In [100]:
del df_dados["colunaErro"]

In [101]:
df_dados

   nome sobrenome  idade genero
0   Téo     Calvo     28      M
1   Nah   Gironde     30      F
2  Lara     Calvo     27      F
3    Ju       Duc     26      F

### Unique e Nunique

In [102]:
df_votacao["sigla_partido"].unique() #lista todos os partidos

array(['PDT', 'PMDB', 'PT', 'PHS', 'PPL', 'PPS', 'PP', 'PSB', 'REDE',
       'DEM', 'PCB', 'PC DO B', 'PCO', 'PMN', 'PR', 'PSDB', 'PEN', 'PRTB',
       'PRB', 'PROS', 'PRP', 'PSC', 'PSDC', 'PSD', 'PSL', 'PSOL', 'PSTU',
       'PTB', 'PTC', 'PT DO B', 'PTN', 'PV', 'SD', 'PODE', 'PMB', 'NOVO',
       'DC', 'MDB', 'PATRI', 'AVANTE', 'SOLIDARIEDADE'], dtype=object)

In [103]:
df_votacao["sigla_partido"].nunique()

41

In [104]:
df_votacao["nome"].nunique()

466435

In [105]:
df_votacao["ano_eleicao"].unique()

array([2014, 2016, 2018])

In [106]:
df_vot_2018 = df_votacao[df_votacao["ano_eleicao"] == 2018]
df_vot_2018
df_vot_2018.columns.tolist()

print(df_vot_2018 ["numero_sequencial"].nunique(), "candidatos distintos em 2018")
print(df_vot_2018 ["nome"].nunique(), "nomes distintos em 2018")

print(df_vot_2018.shape[0], "linhas na base.")


print(df_vot_2018[df_vot_2018["numero_turno"] == 1]["numero_sequencial"].nunique(), "nomes distintos em 2018")
print(df_vot_2018[df_vot_2018["numero_turno"] == 2]["numero_sequencial"].nunique(), "nomes distintos em 2018")

df_vot_2018[df_vot_2018 ["numero_turno"] == 2]["nome"]

26420 candidatos distintos em 2018
26321 nomes distintos em 2018
26450 linhas na base.
26420 nomes distintos em 2018
30 nomes distintos em 2018

484668                        FERNANDO HADDAD
484669                 JAIR MESSIAS BOLSONARO
511077                  EDUARDO DA COSTA PAES
511078      MARCIO DESIDERIO TEIXEIRA MIRANDA
511079                HELDER ZAHLUTH BARBALHO
511080            IBANEIS ROCHA BARROS JUNIOR
511081                       JOSE IVO SARTORI
511082        ANTONIO AUGUSTO JUNHO ANASTASIA
511083    EDUARDO FIGUEIREDO CAVALHEIRO LEITE
511084     EXPEDITO GONCALVES FERREIRA JUNIOR
511085    JOAO AGRIPINO DA COSTA DORIA JUNIOR
511086                JOSE DE ANCHIETA JUNIOR
511087                REINALDO AZAMBUJA SILVA
511088               AMAZONINO ARMANDO MENDES
511089           ANTONIO WALDEZ GOES DA SILVA
511090             CARLOS EDUARDO NUNES ALVES
511091                     ODILON DE OLIVEIRA
511092                MARIA DE FATIMA BEZERRA
511093                        ROMEU ZEMA NETO
511094                     WILSON JOSE WITZEL
511095                    WILSON MIRANDA LIMA
511096                 BELIVALDO CHAGAS SILVA
511097                    GELSON LUIZ MERISIO
511098     ANTONIO OLIVERIO GARCIA DE ALMEIDA
511099                 CARLOS MOISES DA SILVA
511100           MARCOS JOSE ROCHA DOS SANTOS
511101         ANTONIO CARLOS VALADARES FILHO
511102      JOAO ALBERTO RODRIGUES CAPIBERIBE
511103               MARCIO LUIZ FRANCA GOMES
511104              RODRIGO SOBRAL ROLLEMBERG
Name: nome, dtype: object

In [107]:
df_vot_2018.shape[0]

26450

In [108]:
df_vot_2018 [df_vot_2018 ["numero_turno"] == 1]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
484655,2018,ELEICAO GERAL FEDERAL 2018,1,DEMOCRACIA CRISTA,27,DC,PRESIDENTE,APTO,NaN,JOSE MARIA EYMAEL,...,242,1413,325,551,776,822,792,116,859,41710
484656,2018,ELEICAO GERAL FEDERAL 2018,1,MOVIMENTO DEMOCRATICO BRASILEIRO,15,MDB,PRESIDENTE,APTO,NaN,HENRIQUE DE CAMPOS MEIRELLES,...,5324,100724,18154,16761,52214,26939,22232,3426,51670,1288950
484657,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PRESIDENTE,APTO,NaN,GERALDO JOSE RODRIGUES ALCKMIN FILHO,...,21666,229122,90897,47974,50654,53640,79049,19231,154068,5096350
484658,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PRESIDENTE,APTO,NaN,CIRO FERREIRA GOMES,...,54262,415593,112296,211240,282472,266272,195553,14838,264312,13344371
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,311212,1714822,333407,1172147,2062638,190508,495868,49406,598578,31342051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511072,2018,ELEICOES GERAIS ESTADUAIS 2018,1,SOLIDARIEDADE,77,SOLIDARIEDADE,SENADOR,APTO,NaN,DINIS ANTONIO PINHEIRO,...,0,0,0,0,0,0,0,0,0,3251175
511073,2018,ELEICOES GERAIS ESTADUAIS 2018,1,SOLIDARIEDADE,77,SOLIDARIEDADE,SENADOR,APTO,NaN,FERNANDO DE CASTRO MARQUES,...,0,0,0,0,0,124904,0,0,0,124904
511074,2018,ELEICOES GERAIS ESTADUAIS 2018,1,SOLIDARIEDADE,77,SOLIDARIEDADE,SENADOR,APTO,NaN,MARIA MAGNOLIA SOUSA FIGUEIREDO,...,0,0,0,0,0,0,0,0,0,114055
511075,2018,ELEICOES GERAIS ESTADUAIS 2018,1,SOLIDARIEDADE,77,SOLIDARIEDADE,SENADOR,APTO,NaN,SANDRA REGINA MARCOLLA WEBER,...,0,0,0,0,0,0,0,0,0,263411
511076,2018,ELEICOES GERAIS ESTADUAIS 2018,1,SOLIDARIEDADE,77,SOLIDARIEDADE,SENADOR,INAPTO,NaN,WLADIMIR AFONSO DA COSTA RABELO,...,0,0,0,0,0,0,0,0,0,0

## Transformações, conversões e remoções

* Operações com escalares
* Operações entre colunas
* apply()
* funções anônimas

In [109]:
df_votacao.head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680

In [110]:
import numpy as np
df_votacao["log_total_votos"] = np.log1p(df_votacao["total_votos"])
df_votacao["votos_por_mil"] = df_votacao["total_votos"] / 1000
df_votacao["sem_sentido"] = df_votacao["votos_por_mil"] * df_votacao["log_total_votos"]

In [111]:
df_votacao.head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,577397,13.266287,577.397,7659.914363
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,377680,12.841805,377.680,4850.092989

In [112]:
#funcao (nao tem nada a ver com o pandas)
def sigla_to_genero(x):
    if x == "M":
        return "Masculino"
    elif x == "F":
        return "Feminino"
    else:
        return np.nan

sigla_to_genero ("M")

'Masculino'

In [113]:
df_dados

   nome sobrenome  idade genero
0   Téo     Calvo     28      M
1   Nah   Gironde     30      F
2  Lara     Calvo     27      F
3    Ju       Duc     26      F

In [114]:
df_dados["genero_dsc"] = df_dados["genero"].apply( sigla_to_genero)

In [115]:
df_dados

   nome sobrenome  idade genero genero_dsc
0   Téo     Calvo     28      M  Masculino
1   Nah   Gironde     30      F   Feminino
2  Lara     Calvo     27      F   Feminino
3    Ju       Duc     26      F   Feminino

In [116]:
nome = "Teo Calvo"
"Calvo" in nome

True

In [117]:
def is_bolsonaro(x):
    return "BOLSONARO" in x

In [118]:
is_bolsonaro( "EDUARDO BOLSONARO" )

True

In [119]:
df_votacao[df_votacao["nome"].apply(is_bolsonaro)]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido
9787,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO ESTADUAL,DEFERIDO,APTO,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,160359,11.985177,160.359,1.921931e+03
10198,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO FEDERAL,DEFERIDO,APTO,JAIR MESSIAS BOLSONARO,...,0,0,0,0,0,0,464572,13.048874,464.572,6.062141e+03
13519,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIAL CRISTAO,20,PSC,DEPUTADO FEDERAL,DEFERIDO,APTO,EDUARDO NANTES BOLSONARO,...,0,0,0,0,0,0,82224,11.317215,82.224,9.305467e+02
66343,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DA REPUBLICA,22,PR,PREFEITO,DEFERIDO,APTO,RENATO ANTONIO BOLSONARO,...,0,0,0,0,0,0,2473,7.813592,2.473,1.932301e+01
315826,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,PREFEITO,DEFERIDO,APTO,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,424307,12.958215,424.307,5.498261e+03
318201,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,CARLOS NANTES BOLSONARO,...,0,0,0,0,0,0,106657,11.577383,106.657,1.234809e+03
330058,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,VALERIA MULLER RAMOS BOLSONARO,...,0,0,0,0,0,0,620,6.431331,0.620,3.987425e+00
484662,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,346944,817531,936494,1122131,174306,2603665,49277010,17.712968,49277.010,8.728421e+05
484669,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,844190,1773130,2160822,2553222,366536,5932484,115595694,18.565609,115595.694,2.146104e+06
502601,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,DEPUTADO ESTADUAL,APTO,NaN,VALERIA MULLER RAMOS BOLSONARO,...,0,0,0,0,0,0,54519,10.906323,54.519,5.946018e+02
502818,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,DEPUTADO FEDERAL,APTO,NaN,EDUARDO NANTES BOLSONARO,...,0,0,0,0,0,0,1843735,14.427305,1843.735,2.660013e+04
503176,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,SENADOR,APTO,NaN,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,4380418,15.292655,4380.418,6.698822e+04

In [120]:
def like(x, like_what = ""):
    return like_what in x

In [121]:
df_votacao[df_votacao["nome"].apply(like, args=["SILVA"])]
like("Nah Ataide", like_what="Calvo")

False

In [122]:
#df_votacao [df_votacao ["nome"].apply (like, args=["HADDAD"])]
df_votacao[df_votacao["nome"].apply(like, args=["BOLSONARO"])].head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido
9787,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO ESTADUAL,DEFERIDO,APTO,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,160359,11.985177,160.359,1921.930929
10198,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO FEDERAL,DEFERIDO,APTO,JAIR MESSIAS BOLSONARO,...,0,0,0,0,0,0,464572,13.048874,464.572,6062.141484

In [123]:
#funcao anonima
df_votacao[df_votacao["nome"].apply( lambda x :  "HADDAD" in x)]
df_votacao[df_votacao["nome"].apply( lambda x :  "BOLSONARO" in x)]
df_votacao[df_votacao["nome"].apply( lambda x :  "BOLSONARO" in x or "HADDAD" in x)]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido
3577,2014,ELEICOES GERAIS 2014,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO FEDERAL,DEFERIDO,APTO,MIGUEL MOUBADDA HADDAD,...,0,0,0,0,0,0,168278,12.033379,168.278,2.024953e+03
4162,2014,ELEICOES GERAIS 2014,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,DEPUTADO ESTADUAL,DEFERIDO,APTO,NACIB HADDAD NETO,...,0,0,0,18087,0,0,18087,9.803004,18.087,1.773069e+02
9787,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO ESTADUAL,DEFERIDO,APTO,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,160359,11.985177,160.359,1.921931e+03
10198,2014,ELEICOES GERAIS 2014,1,PARTIDO PROGRESSISTA,11,PP,DEPUTADO FEDERAL,DEFERIDO,APTO,JAIR MESSIAS BOLSONARO,...,0,0,0,0,0,0,464572,13.048874,464.572,6.062141e+03
11542,2014,ELEICOES GERAIS 2014,1,PARTIDO REPUBLICANO BRASILEIRO,10,PRB,DEPUTADO FEDERAL,DEFERIDO,APTO,SAMIR HADDAD JUNIOR,...,0,0,0,0,0,0,554,6.318968,0.554,3.500708e+00
13519,2014,ELEICOES GERAIS 2014,1,PARTIDO SOCIAL CRISTAO,20,PSC,DEPUTADO FEDERAL,DEFERIDO,APTO,EDUARDO NANTES BOLSONARO,...,0,0,0,0,0,0,82224,11.317215,82.224,9.305467e+02
41953,2016,ELEICOES MUNICIPAIS 2016,1,DEMOCRATAS,25,DEM,VEREADOR,DEFERIDO,APTO,VICTOR TANNUS HADDAD,...,0,0,0,0,0,0,34,3.555348,0.034,1.208818e-01
66343,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DA REPUBLICA,22,PR,PREFEITO,DEFERIDO,APTO,RENATO ANTONIO BOLSONARO,...,0,0,0,0,0,0,2473,7.813592,2.473,1.932301e+01
83219,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DA REPUBLICA,22,PR,VEREADOR,DEFERIDO,APTO,RICARDO HADDAD MUNIZ,...,0,0,0,0,0,154,154,5.043425,0.154,7.766875e-01
88066,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,PREFEITO,DEFERIDO,APTO,NAIEF HADDAD NETO,...,0,0,0,0,0,0,4337,8.375169,4.337,3.632311e+01
102493,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,VEREADOR,DEFERIDO,APTO,JOAO CHADDAD,...,0,0,0,0,0,0,365,5.902633,0.365,2.154461e+00
120642,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,PREFEITO,DEFERIDO,APTO,JOEL DAVID HADDAD,...,0,0,0,0,0,0,9592,9.168789,9.592,8.794702e+01
138170,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,VEREADOR,DEFERIDO,APTO,NACIB HADDAD NETO,...,0,0,0,3282,0,0,3282,8.096513,3.282,2.657276e+01
178451,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,VEREADOR,DEFERIDO,APTO,REGINA HADDAD BARRACH ZABALIA,...,0,0,0,0,0,0,594,6.388561,0.594,3.794805e+00
180624,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,VEREADOR,DEFERIDO,APTO,SAMIR HADDAD JUNIOR,...,0,0,0,0,0,0,59,4.094345,0.059,2.415663e-01
186242,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO DOS TRABALHADORES,13,PT,PREFEITO,DEFERIDO,APTO,FERNANDO HADDAD,...,0,0,0,0,0,0,967190,13.782151,967.190,1.332996e+04
237355,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO POPULAR SOCIALISTA,23,PPS,VEREADOR,DEFERIDO,APTO,ESTEVAO EDMAR HADDAD CAMOLESI JUNIOR,...,0,0,0,0,0,0,4598,8.433594,4.598,3.877767e+01
242724,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO POPULAR SOCIALISTA,23,PPS,VEREADOR,DEFERIDO,APTO,MARCOS FELIPI HADDAD DE MENEZES GARCIA,...,0,0,0,0,0,0,895,6.797940,0.895,6.084157e+00
244587,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO POPULAR SOCIALISTA,23,PPS,VEREADOR,DEFERIDO,APTO,PAULO CESAR HADDAD,...,0,0,0,0,0,0,3118,8.045268,3.118,2.508514e+01
309129,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO REPUBLICANO PROGRESSISTA,44,PRP,VEREADOR,DEFERIDO,APTO,CLAUDIA ANGELA HADDAD CURTI,...,0,0,0,0,0,0,6,1.945910,0.006,1.167546e-02
311351,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO REPUBLICANO PROGRESSISTA,44,PRP,VEREADOR,DEFERIDO,APTO,JOAO CHADDAD,...,0,0,0,0,0,0,146,4.990433,0.146,7.286032e-01
315826,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,PREFEITO,DEFERIDO,APTO,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,424307,12.958215,424.307,5.498261e+03
318057,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,CARLA HADDAD PEREIRA,...,0,0,0,0,0,0,155,5.049856,0.155,7.827277e-01
318201,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,CARLOS NANTES BOLSONARO,...,0,0,0,0,0,0,106657,11.577383,106.657,1.234809e+03
330058,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,VALERIA MULLER RAMOS BOLSONARO,...,0,0,0,0,0,0,620,6.431331,0.620,3.987425e+00
330614,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL CRISTAO,20,PSC,VEREADOR,DEFERIDO,APTO,WILLIAN SCHLEICH HADDAD,...,0,0,0,0,0,0,19,2.995732,0.019,5.691891e-02
354069,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL DEMOCRATICO,55,PSD,VEREADOR,DEFERIDO,APTO,KAREN HADDAD GEORGES,...,0,0,0,0,0,0,89,4.499810,0.089,4.004831e-01
358702,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO SOCIAL DEMOCRATICO,55,PSD,VEREADOR,DEFERIDO,APTO,MONIQUE HADDAD ARAUJO PATZLAFF,...,0,0,0,0,0,0,156,5.056246,0.156,7.887743e-01
417366,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO TRABALHISTA BRASILEIRO,14,PTB,VEREADOR,DEFERIDO,APTO,JULIO CESAR HADDAD,...,0,0,0,0,0,0,222,5.407172,0.222,1.200392e+00
428404,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO TRABALHISTA CRISTAO,36,PTC,VEREADOR,DEFERIDO,APTO,DANIELA CHADDAD RAINERI,...,0,0,0,0,0,0,288,5.666427,0.288,1.631931e+00
463668,2016,ELEICOES MUNICIPAIS 2016,1,PARTIDO VERDE,43,PV,VEREADOR,DEFERIDO,APTO,RAFAEL LEITE HADDAD,...,0,0,0,0,0,0,57,4.060443,0.057,2.314453e-01
467127,2016,ELEICOES MUNICIPAIS 2016,1,REDE SUSTENTABILIDADE,18,REDE,PREFEITO,DEFERIDO,APTO,RAFAEL HADDAD MANFIO,...,0,0,0,0,0,0,4556,8.424420,4.556,3.838166e+01
484659,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,1172147,2062638,190508,495868,49406,598578,31342051,17.260471,31342.051,5.409786e+05
484662,2018,ELEICAO GERAL FEDERAL 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,346944,817531,936494,1122131,174306,2603665,49277010,17.712968,49277.010,8.728421e+05
484668,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO DOS TRABALHADORES,13,PT,PRESIDENTE,APTO,NaN,FERNANDO HADDAD,...,2834226,4857826,926680,1495536,145744,1881448,94081812,18.359675,94081.812,1.727312e+06
484669,2018,ELEICAO GERAL FEDERAL 2018,2,PARTIDO SOCIAL LIBERAL,17,PSL,PRESIDENTE,APTO,NaN,JAIR MESSIAS BOLSONARO,...,844190,1773130,2160822,2553222,366536,5932484,115595694,18.565609,115595.694,2.146104e+06
491353,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,45,PSDB,DEPUTADO FEDERAL,APTO,NaN,MIGUEL MOUBADDA HADDAD,...,0,0,0,0,0,0,86042,11.362602,86.042,9.776610e+02
502601,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,DEPUTADO ESTADUAL,APTO,NaN,VALERIA MULLER RAMOS BOLSONARO,...,0,0,0,0,0,0,54519,10.906323,54.519,5.946018e+02
502818,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,DEPUTADO FEDERAL,APTO,NaN,EDUARDO NANTES BOLSONARO,...,0,0,0,0,0,0,1843735,14.427305,1843.735,2.660013e+04
503176,2018,ELEICOES GERAIS ESTADUAIS 2018,1,PARTIDO SOCIAL LIBERAL,17,PSL,SENADOR,APTO,NaN,FLAVIO NANTES BOLSONARO,...,0,0,0,0,0,0,4380418,15.292655,4380.418,6.698822e+04

In [124]:
"Téo Balbino Calvo".split(" ")[0]. title() #title deixa a primeira letra maiscula

'Téo'

In [125]:
"Téo Balbino Calvo".split(" ")

['Téo', 'Balbino', 'Calvo']

In [126]:
df_votacao["nome"].apply(lambda x: x.split(" ")[0]. title() )

0         Amazonino
1            Carlos
2              Jose
3          Mauricio
4         Jadelvone
            ...
511100       Marcos
511101      Antonio
511102         Joao
511103       Marcio
511104      Rodrigo
Name: nome, Length: 511105, dtype: object

In [127]:
"eu amo o meu namorado".title()

'Eu Amo O Meu Namorado'

In [128]:
df_votacao["primeiro_nome"] = df_votacao["nome"].apply(lambda x: x.split(" ")[0]. title() )

In [129]:
df_votacao.head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido,primeiro_nome
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,577397,13.266287,577.397,7659.914363,Amazonino
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,377680,12.841805,377.680,4850.092989,Carlos

## Group by & Sort by

* Operações Estatísticas: sum, mean, count, std...
* Agrupando por chave

### Sintaxe genérica
df.groupby()

In [130]:
#tabela de frequencia
pd.value_counts(df_dados ["sobrenome"]) #quantas pessoas com o mesmo sobrenome
#df_dados["sobrenome"].value_counts() #vale também

Calvo      2
Duc        1
Gironde    1
Name: sobrenome, dtype: int64

In [131]:
print(df_dados["idade"].mean(), "Media") # Media 
print(df_dados["idade"].sum(), "Soma") # Soma
print(df_dados["idade"].std(), "Desvio padrão") # Desvio padrão
print()
print(df_dados["idade"].min(), "min") # min
print(df_dados["idade"].max(), "max") # max
print()
print(df_dados["idade"].describe(), "Sumário") # Summario

27.75 Media
111 Soma
1.707825127659933 Desvio padrão

26 min
30 max

count     4.000000
mean     27.750000
std       1.707825
min      26.000000
25%      26.750000
50%      27.500000
75%      28.500000
max      30.000000
Name: idade, dtype: float64 Sumário

In [132]:
#fill na para converter NA em "valor ausente"

In [133]:
df_dados.groupby(["sobrenome"])["idade"].mean()

sobrenome
Calvo      27.5
Duc        26.0
Gironde    30.0
Name: idade, dtype: float64

In [134]:
df_dados.groupby(["sobrenome"])["idade"].describe()

           count  mean       std   min    25%   50%    75%   max
sobrenome
Calvo        2.0  27.5  0.707107  27.0  27.25  27.5  27.75  28.0
Duc          1.0  26.0       NaN  26.0  26.00  26.0  26.00  26.0
Gironde      1.0  30.0       NaN  30.0  30.00  30.0  30.00  30.0

In [135]:
df_dados.groupby(["sobrenome"]).agg ({"idade": ["mean", "sum"]})

          idade
           mean sum
sobrenome
Calvo      27.5  55
Duc        26.0  26
Gironde    30.0  30

In [136]:
df_dados.groupby(["sobrenome"]).agg ({"idade": ["sum", "describe"]})

          idade
            sum describe
          idade    count  mean       std   min    25%   50%    75%   max
sobrenome
Calvo        55      2.0  27.5  0.707107  27.0  27.25  27.5  27.75  28.0
Duc          26      1.0  26.0       NaN  26.0  26.00  26.0  26.00  26.0
Gironde      30      1.0  30.0       NaN  30.0  30.00  30.0  30.00  30.0

In [137]:
#multi index column - pesquisar

# Quanto cada partido teve de votos totais em cada ano de eleicao em cada turno?

In [138]:
agg_columns = ["ano_eleicao", "numero_turno", "sigla_partido"]
df_group = df_votacao.groupby(agg_columns)["total_votos"].sum().head(50)

In [139]:
df_group

ano_eleicao  numero_turno  sigla_partido
2014         1             DEM               13644709
                           PC DO B            7110362
                           PCB                 270270
                           PCO                  54507
                           PDT               13036163
                           PEN                2158817
                           PHS                2147026
                           PMDB              55073506
                           PMN                1257861
                           PP                14330741
                           PPL                 560105
                           PPS                3854357
                           PR                11832004
                           PRB                8501392
                           PROS               7041618
                           PRP                1905284
                           PRTB               1681267
                           PSB               52402048
                           PSC                6737463
                           PSD               21140494
                           PSDB             103432738
                           PSDC               1359895
                           PSL                2213987
                           PSOL               7411511
                           PSTU                836982
                           PT               102239868
                           PT DO B            1917630
                           PTB               11102062
                           PTC                1328023
                           PTN                2185297
                           PV                 6300115
                           REDE                 39240
                           SD                 5312229
             2             PDT                1003189
                           PMDB              15726432
                           PP                  127161
                           PR                  649587
                           PRB                3442713
                           PROS                869992
                           PSB                2185959
                           PSD                 877268
                           PSDB              56959640
                           PT                60159420
2016         1             DEM                9560798
                           NOVO                307391
                           PC DO B            4120997
                           PCB                  46597
                           PCO                   8963
                           PDT               12048116
                           PEN                1863883
Name: total_votos, dtype: int64

In [140]:
df_group.loc[2014][1]["PT"]

102239868

In [141]:
df_group = df_group.reset_index()

In [142]:
#pd.set_option('display.max_rows', 500) #mostra tudo
#pd.set_option('display.max_rows', 25) #mostra tudo
df_group.sort_values( by = ["ano_eleicao", "total_votos"], ascending = [True, False]).head()

    ano_eleicao  numero_turno sigla_partido  total_votos
20         2014             1          PSDB    103432738
25         2014             1            PT    102239868
42         2014             2            PT     60159420
41         2014             2          PSDB     56959640
7          2014             1          PMDB     55073506

In [143]:
df_group.sort_values(by = ["ano_eleicao", "total_votos"], ascending = [True, False])

    ano_eleicao  numero_turno sigla_partido  total_votos
20         2014             1          PSDB    103432738
25         2014             1            PT    102239868
42         2014             2            PT     60159420
41         2014             2          PSDB     56959640
7          2014             1          PMDB     55073506
17         2014             1           PSB     52402048
19         2014             1           PSD     21140494
34         2014             2          PMDB     15726432
9          2014             1            PP     14330741
0          2014             1           DEM     13644709
4          2014             1           PDT     13036163
12         2014             1            PR     11832004
27         2014             1           PTB     11102062
13         2014             1           PRB      8501392
23         2014             1          PSOL      7411511
1          2014             1       PC DO B      7110362
14         2014             1          PROS      7041618
18         2014             1           PSC      6737463
30         2014             1            PV      6300115
32         2014             1            SD      5312229
11         2014             1           PPS      3854357
37         2014             2           PRB      3442713
22         2014             1           PSL      2213987
39         2014             2           PSB      2185959
29         2014             1           PTN      2185297
5          2014             1           PEN      2158817
6          2014             1           PHS      2147026
26         2014             1       PT DO B      1917630
15         2014             1           PRP      1905284
16         2014             1          PRTB      1681267
21         2014             1          PSDC      1359895
28         2014             1           PTC      1328023
8          2014             1           PMN      1257861
33         2014             2           PDT      1003189
40         2014             2           PSD       877268
38         2014             2          PROS       869992
24         2014             1          PSTU       836982
36         2014             2            PR       649587
10         2014             1           PPL       560105
2          2014             1           PCB       270270
35         2014             2            PP       127161
3          2014             1           PCO        54507
31         2014             1          REDE        39240
48         2016             1           PDT     12048116
43         2016             1           DEM      9560798
45         2016             1       PC DO B      4120997
49         2016             1           PEN      1863883
44         2016             1          NOVO       307391
46         2016             1           PCB        46597
47         2016             1           PCO         8963

## Stack e Unstack

* Empilhando e desempilhando dados

### Sintaxe geral
df.stack()
df.unstack()
df.explode()

In [146]:
df_group = df_group.sort_values(by = ["ano_eleicao", "total_votos"], ascending = [True, False])

In [147]:
df_group = df_group.set_index([ "ano_eleicao", "numero_turno", "sigla_partido"])
df_group

                                        total_votos
ano_eleicao numero_turno sigla_partido
2014        1            PSDB             103432738
                         PT               102239868
            2            PT                60159420
                         PSDB              56959640
            1            PMDB              55073506
                         PSB               52402048
                         PSD               21140494
            2            PMDB              15726432
            1            PP                14330741
                         DEM               13644709
                         PDT               13036163
                         PR                11832004
                         PTB               11102062
                         PRB                8501392
                         PSOL               7411511
                         PC DO B            7110362
                         PROS               7041618
                         PSC                6737463
                         PV                 6300115
                         SD                 5312229
                         PPS                3854357
            2            PRB                3442713
            1            PSL                2213987
            2            PSB                2185959
            1            PTN                2185297
                         PEN                2158817
                         PHS                2147026
                         PT DO B            1917630
                         PRP                1905284
                         PRTB               1681267
                         PSDC               1359895
                         PTC                1328023
                         PMN                1257861
            2            PDT                1003189
                         PSD                 877268
                         PROS                869992
            1            PSTU                836982
            2            PR                  649587
            1            PPL                 560105
                         PCB                 270270
            2            PP                  127161
            1            PCO                  54507
                         REDE                 39240
2016        1            PDT               12048116
                         DEM                9560798
                         PC DO B            4120997
                         PEN                1863883
                         NOVO                307391
                         PCB                  46597
                         PCO                   8963

In [148]:
df_unstack = df_group.unstack().fillna(0)
df_unstack

                         total_votos                                          \
sigla_partido                    DEM      NOVO    PC DO B       PCB      PCO
ano_eleicao numero_turno
2014        1             13644709.0       0.0  7110362.0  270270.0  54507.0
            2                    0.0       0.0        0.0       0.0      0.0
2016        1              9560798.0  307391.0  4120997.0   46597.0   8963.0

                                                                        \
sigla_partido                    PDT        PEN        PHS        PMDB
ano_eleicao numero_turno
2014        1             13036163.0  2158817.0  2147026.0  55073506.0
            2              1003189.0        0.0        0.0  15726432.0
2016        1             12048116.0  1863883.0        0.0         0.0

                                     ...                                    \
sigla_partido                   PMN  ...       PSOL      PSTU           PT
ano_eleicao numero_turno             ...
2014        1             1257861.0  ...  7411511.0  836982.0  102239868.0
            2                   0.0  ...        0.0       0.0   60159420.0
2016        1                   0.0  ...        0.0       0.0          0.0

                                                                       \
sigla_partido               PT DO B         PTB        PTC        PTN
ano_eleicao numero_turno
2014        1             1917630.0  11102062.0  1328023.0  2185297.0
            2                   0.0         0.0        0.0        0.0
2016        1                   0.0         0.0        0.0        0.0


sigla_partido                    PV     REDE         SD
ano_eleicao numero_turno
2014        1             6300115.0  39240.0  5312229.0
            2                   0.0      0.0        0.0
2016        1                   0.0      0.0        0.0

[3 rows x 34 columns]

In [149]:
df_unstack.stack()

                                        total_votos
ano_eleicao numero_turno sigla_partido
2014        1            DEM             13644709.0
                         NOVO                   0.0
                         PC DO B          7110362.0
                         PCB               270270.0
                         PCO                54507.0
...                                             ...
2016        1            PTC                    0.0
                         PTN                    0.0
                         PV                     0.0
                         REDE                   0.0
                         SD                     0.0

[102 rows x 1 columns]

In [150]:
# explode
df_dados["empregos"] = [ [ "Via Varejo", "Téo Me Why", "ASN"],
                         ["studio.artesanah"],
                         ["Fiscal de Obra", "Arquiteta"],
                         ["PagSeguro"] ]                        

df_dados

   nome sobrenome  idade genero genero_dsc                       empregos
0   Téo     Calvo     28      M  Masculino  [Via Varejo, Téo Me Why, ASN]
1   Nah   Gironde     30      F   Feminino             [studio.artesanah]
2  Lara     Calvo     27      F   Feminino    [Fiscal de Obra, Arquiteta]
3    Ju       Duc     26      F   Feminino                    [PagSeguro]

In [151]:
# Explode a porra toda
df_dados.explode("empregos")

   nome sobrenome  idade genero genero_dsc          empregos
0   Téo     Calvo     28      M  Masculino        Via Varejo
0   Téo     Calvo     28      M  Masculino        Téo Me Why
0   Téo     Calvo     28      M  Masculino               ASN
1   Nah   Gironde     30      F   Feminino  studio.artesanah
2  Lara     Calvo     27      F   Feminino    Fiscal de Obra
2  Lara     Calvo     27      F   Feminino         Arquiteta
3    Ju       Duc     26      F   Feminino         PagSeguro

In [152]:
df_dados.groupby("nome").agg({"empregos" : lambda x: list(x) [0]})

                           empregos
nome
Ju                      [PagSeguro]
Lara    [Fiscal de Obra, Arquiteta]
Nah              [studio.artesanah]
Téo   [Via Varejo, Téo Me Why, ASN]

## Joins

* merge com left, right, inner, etc.
* 'on' como chave

* Falar de concat

In [153]:
df_votacao.head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido,primeiro_nome
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,577397,13.266287,577.397,7659.914363,Amazonino
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,377680,12.841805,377.680,4850.092989,Carlos

In [154]:
df_group.head(2)

                                        total_votos
ano_eleicao numero_turno sigla_partido
2014        1            PSDB             103432738
                         PT               102239868

In [155]:
type(df_group)

pandas.core.frame.DataFrame

In [156]:
df_group = df_group.reset_index()
df_group.head(2)

   ano_eleicao  numero_turno sigla_partido  total_votos
0         2014             1          PSDB    103432738
1         2014             1            PT    102239868

In [157]:
df_vot_join = df_votacao.merge( 
                  right = df_group,
                  on = ["ano_eleicao", "numero_turno", "sigla_partido"],
                  how = "left",
                  suffixes = ["", "_partido"])

df_vot_join.head()

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido,primeiro_nome,total_votos_partido
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,577397,13.266287,577.397,7659.914363,Amazonino,13036163.0
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,377680,12.841805,377.680,4850.092989,Carlos,55073506.0
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,181257,12.107677,181.257,2194.601157,Jose,102239868.0
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,22623,10.026767,22.623,226.835540,Mauricio,2147026.0
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,3362,8.120589,3.362,27.301419,Jadelvone,560105.0

In [158]:
df_vot_join["representacao_partido"] = df_vot_join["total_votos"] / df_vot_join ["total_votos_partido"]
df_vot_join.head(2)

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_es,total_votos_rr,total_votos_sc,total_votos,log_total_votos,votos_por_mil,sem_sentido,primeiro_nome,total_votos_partido,representacao_partido
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,577397,13.266287,577.397,7659.914363,Amazonino,13036163.0,0.044292
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,377680,12.841805,377.680,4850.092989,Carlos,55073506.0,0.006858

In [159]:
df_dados.reset_index()
#df_dados.reset_index(drop=True)

,index,nome,sobrenome,idade,genero,genero_dsc,empregos
0,0,Téo,Calvo,28,M,Masculino,"[Via Varejo, Téo Me Why, ASN]"
1,1,Nah,Gironde,30,F,Feminino,[studio.artesanah]
2,2,Lara,Calvo,27,F,Feminino,"[Fiscal de Obra, Arquiteta]"
3,3,Ju,Duc,26,F,Feminino,[PagSeguro]

In [160]:
# Análise de qual partido tem mais bens declarados
df_bens = pd.read_excel( "../data/tb_bens.xlsx" )
df_bens.head(2)

,ano_eleicao,codigo_eleicao,codigo_tipo_eleicao,data_eleicao,descricao_eleicao,nome_tipo_eleicao,nome_ue,sigla_ue,sigla_uf,numero_sequencial,codigo_tipo,data_ultima_atualizacao,descricao_tipo,detalhe,hora_ultima_atualizacao,numero_ordem,valor
0,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,32,12/07/2018,QUOTAS OU QUINHOES DE CAPITAL,8360 QUOTAS DE CAPITAL SOCIAL DA EMPRESA MARMU...,16:36:00,1,8360.0
1,2014,143,2,05/10/2014,ELEICOES GERAIS 2014,ELEICAO ORDINARIA,ACRE,AC,AC,10000000001,21,12/07/2018,"VEICULO AUTOMOTOR TERRESTRE: CAMINHAO, AUTOMOV...","AUTOMOVEL HILUX CD,",16:36:00,2,143000.0

In [161]:
df_votos = pd.read_csv( "../data/votacao_agg_estado.csv")
df_votos.head(2)

/home/teo/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680

In [162]:
df_bens[df_bens["ano_eleicao"] == 2018]
df_bens[df_bens["ano_eleicao"] == 2018].shape
df_bens[df_bens["ano_eleicao"] == 2018]["numero_sequencial"].nunique()

17614

In [163]:
df_total_bens = df_bens.groupby(["ano_eleicao", "descricao_eleicao", "numero_sequencial" ])["valor"].sum()
df_total_bens

ano_eleicao  descricao_eleicao                    numero_sequencial
2014         ELEICAO SUPLEMENTAR GOVERNADOR - TO  270000010427          3851225.78
                                                  270000010428         89443068.71
                                                  270000010429         15703130.86
                                                  270000010430          1139685.88
                                                  270000010431         18943005.55
                                                                          ...
2018         ELEICOES GERAIS ESTADUAIS 2018       270000627773           205000.00
                                                  270000627774           200000.00
                                                  270000628397           615000.00
                                                  270000628492           685000.00
                                                  270000629137          1647689.26
Name: valor, Length: 32915, dtype: float64

In [164]:
# importa os votos dos candidatos por turno
df_votos = pd.read_csv("../data/votacao_agg_estado.csv")

/home/teo/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [165]:
df_votos = df_votos.merge( right=df_total_bens,
                           on=["ano_eleicao", "descricao_eleicao", "numero_sequencial"],
                           how="left" )
df_votos.head(2)
#checando se deu certo
#df_votos [ (df_votos ["ano_eleicao"] == 2018 ) & (df_votos["nome"].apply (lambda x: "BOLSONARO" in x))]

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos,valor
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,577397,3273469.94
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,377680,31251331.95

In [166]:
df_votos.groupby(["sigla_partido"])["valor"].sum().reset_index()

    sigla_partido         valor
0          AVANTE  2.464425e+08
1              DC  1.768127e+08
2             DEM  1.132037e+09
3             MDB  1.531635e+09
4            NOVO  1.150842e+09
5           PATRI  2.595275e+08
6         PC DO B  2.918904e+08
7             PCB  1.722598e+07
8             PCO  7.317898e+06
9             PDT  1.484046e+09
10            PEN  1.706307e+08
11            PHS  4.485621e+08
12            PMB  7.047954e+07
13           PMDB  2.273467e+09
14            PMN  3.525309e+08
15           PODE  7.276176e+08
16             PP  1.137303e+09
17            PPL  1.952072e+08
18            PPS  4.230817e+08
19             PR  9.611232e+08
20            PRB  4.549252e+08
21           PROS  3.904561e+09
22            PRP  3.515429e+08
23           PRTB  2.735427e+08
24            PSB  1.252260e+09
25            PSC  6.152697e+08
26            PSD  1.397626e+09
27           PSDB  2.748438e+09
28           PSDC  9.623039e+07
29            PSL  1.541065e+09
30           PSOL  3.485347e+08
31           PSTU  2.589104e+07
32             PT  9.093563e+08
33        PT DO B  1.374558e+08
34            PTB  9.115828e+08
35            PTC  2.773772e+08
36            PTN  1.225125e+08
37             PV  9.750458e+08
38           REDE  1.196219e+09
39             SD  2.132388e+08
40  SOLIDARIEDADE  9.278055e+08

In [167]:
# ordenamos para tirar duplicatas
df_analysis = df_votos.sort_values(by = ["ano_eleicao", "numero_sequencial", "numero_turno"])

colunas_interesse = ["ano_eleicao",
                     "descricao_eleicao",
                     "sigla_partido",
                     "nome",
                     "numero_turno",
                     "numero_sequencial",
                      "valor"]
             
df_analysis = df_analysis[colunas_interesse]
  
df_analysis = df_analysis.drop_duplicates( subset = [ "ano_eleicao", "numero_sequencial"],
                                           keep="first" )

In [168]:
df_analysis[(df_analysis["ano_eleicao"]==2018) & (df_analysis["nome"].apply(lambda x: "BOLSONARO" in x))]

,ano_eleicao,descricao_eleicao,sigla_partido,nome,numero_turno,numero_sequencial,valor
503176,2018,ELEICOES GERAIS ESTADUAIS 2018,PSL,FLAVIO NANTES BOLSONARO,1,190000614721,1741758.15
502601,2018,ELEICOES GERAIS ESTADUAIS 2018,PSL,VALERIA MULLER RAMOS BOLSONARO,1,250000613301,17950.12
502818,2018,ELEICOES GERAIS ESTADUAIS 2018,PSL,EDUARDO NANTES BOLSONARO,1,250000613378,1395109.14
484662,2018,ELEICAO GERAL FEDERAL 2018,PSL,JAIR MESSIAS BOLSONARO,1,280000614517,2286779.48

In [169]:
pd.options.display.float_format = '${:,.2f}'.format
df_resultado = df_analysis.groupby([ "ano_eleicao", "sigla_partido"])["valor"].sum().reset_index()

In [170]:
#salvando no arquivo excel
df_resultado.to_excel("../data/resultado_analise_partido_juliana.xlsx")

## Integração com banco de dados SQL

* Enviando query para o banco
* Consumindo tabela do banco
* Enviando dados para o banco

In [171]:
#instalar o pacote sqlalchemy
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /home/teo/anaconda3/lib/python3.8/site-packages (1.3.18)

In [172]:
import sqlalchemy

In [173]:
# criando engine de conexão
con = sqlalchemy.create_engine("sqlite:///../data/banco.db")

# tabelas que estao presentes no banco
con.table_names()

['tb_bens', 'tb_candidatura', 'tb_patrimonio_partido', 'tb_votacao']

In [174]:
df_bens = pd.read_sql_table ("tb_bens", con)
df_bens.shape

(176321, 17)

In [175]:
df_votos = pd.read_sql_table ("tb_votacao", con)
df_votos.shape

(511105, 43)

In [176]:
df_head = pd.read_sql_query( "SELECT * FROM tb_votacao limit 10", con )
df_head

,ano_eleicao,descricao_eleicao,numero_turno,nome_partido,numero_partido,sigla_partido,descricao_cargo,descricao_situacao_candidatura,descricao_situacao_candidatura_superior,nome,...,total_votos_to,total_votos_pa,total_votos_ms,total_votos_pi,total_votos_ma,total_votos_df,total_votos_es,total_votos_rr,total_votos_sc,total_votos
0,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,577397
1,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO,15,PMDB,GOVERNADOR,DEFERIDO,APTO,CARLOS EDUARDO DE SOUZA BRAGA,...,0,0,0,0,0,0,0,0,0,377680
2,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO DOS TRABALHADORES,13,PT,GOVERNADOR,DEFERIDO,APTO,JOSE RICARDO WENDLING,...,0,0,0,0,0,0,0,0,0,181257
3,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO HUMANISTA DA SOLIDARIEDADE,31,PHS,GOVERNADOR,DEFERIDO,APTO,MAURICIO WILKER DE AZEVEDO BARRETO,...,0,0,0,0,0,0,0,0,0,22623
4,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PATRIA LIVRE,54,PPL,GOVERNADOR,DEFERIDO,APTO,JADELVONE NOGUEIRA DELTRUDES,...,0,0,0,0,0,0,0,0,0,3362
5,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO POPULAR SOCIALISTA,23,PPS,GOVERNADOR,INDEFERIDO COM RECURSO,APTO,LILIANE ARAUJO DE ALMEIDA,...,0,0,0,0,0,0,0,0,0,0
6,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO PROGRESSISTA,11,PP,GOVERNADOR,SUBSTITUTO PENDENTE DE JULGAMENTO,APTO,REBECCA MARTINS GARCIA,...,0,0,0,0,0,0,0,0,0,268922
7,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,PARTIDO SOCIALISTA BRASILEIRO,40,PSB,GOVERNADOR,DEFERIDO,APTO,MARCELO AUGUSTO DA EIRA CORREA,...,0,0,0,0,0,0,0,0,0,18877
8,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,1,REDE SUSTENTABILIDADE,18,REDE,GOVERNADOR,DEFERIDO,APTO,LUIZ CASTRO ANDRADE NETO,...,0,0,0,0,0,0,0,0,0,39240
9,2014,ELEICAO SUPLEMENTAR GOVERNADOR AM,2,PARTIDO DEMOCRATICO TRABALHISTA,12,PDT,GOVERNADOR,DEFERIDO,APTO,AMAZONINO ARMANDO MENDES,...,0,0,0,0,0,0,0,0,0,782933

In [177]:
query = '''

select t1.ano_eleicao,
       t1.sigla_partido,
       t1.nome,
       t1.numero_sequencial,
       sum(t2.valor) as valor

from tb_votacao as t1

left join tb_bens as t2
on t1.ano_eleicao = t2.ano_eleicao
and t1.descricao_eleicao = t2.descricao_eleicao
and t1.numero_sequencial = t2.numero_sequencial

where t1.numero_turno = 1

group by t1.ano_eleicao,
         t1.sigla_partido,
         t1.nome,
         t1.numero_sequencial

'''
df_resposta = pd.read_sql_query(query, con)
df_resposta

,ano_eleicao,sigla_partido,nome,numero_sequencial,valor
0,2014,DEM,ADAGLION AIRES DE ANDRADE,70000001086,"$662,000.00"
1,2014,DEM,ADAIL ALVES CELESTINO,40000000482,$nan
2,2014,DEM,ADEILDO ALVES VILELA,190000001043,"$11,000,000.00"
3,2014,DEM,ADELINO ANGELO FOLLADOR,220000000072,"$1,582,527.67"
4,2014,DEM,ADENOR DE SOUZA FIGUEIRA,40000000428,"$200,000.00"
...,...,...,...,...,...
510924,2018,SOLIDARIEDADE,WLADIMIR AFONSO DA COSTA RABELO,140000605248,"$2,139,658.19"
510925,2018,SOLIDARIEDADE,WOLFANG ANTONINO OJEDA,120000615411,"$20,000.00"
510926,2018,SOLIDARIEDADE,YHGOR LEONARDO CASTRO LEITE,270000618872,"$377,080.00"
510927,2018,SOLIDARIEDADE,YONNY PEDROSO DA SILVA,230000602458,"$759,500.00"
510928,2018,SOLIDARIEDADE,YORANN CHRISTIE BRAGA DA COSTA,140000613804,"$1,892,401.85"

In [178]:
df_analysis = df_resposta.groupby([ "ano_eleicao", "sigla_partido"])["valor"].sum().reset_index() 
df_analysis

     ano_eleicao  sigla_partido             valor
0           2014            DEM   $386,048,089.81
1           2014        PC DO B   $146,995,871.55
2           2014            PCB    $10,507,337.52
3           2014            PCO       $742,150.00
4           2014            PDT   $470,827,805.52
..           ...            ...               ...
99          2018            PTB   $342,213,791.87
100         2018            PTC   $137,771,162.42
101         2018             PV   $703,288,700.24
102         2018           REDE $1,195,373,329.89
103         2018  SOLIDARIEDADE   $927,805,527.59

[104 rows x 3 columns]

In [179]:
df_analysis.to_sql("tb_patrimonio_partido", con, if_exists="replace", index=False)

In [180]:
con.table_names()

['tb_bens', 'tb_candidatura', 'tb_patrimonio_partido', 'tb_votacao']

In [181]:
df_pat = pd.read_sql_query("SELECT * FROM tb_patrimonio_partido limit 10", con)
df_pat

   ano_eleicao sigla_partido             valor
0         2014           DEM   $386,048,089.81
1         2014       PC DO B   $146,995,871.55
2         2014           PCB    $10,507,337.52
3         2014           PCO       $742,150.00
4         2014           PDT   $470,827,805.52
5         2014           PEN   $170,630,725.70
6         2014           PHS   $178,513,005.94
7         2014          PMDB $2,074,025,844.36
8         2014           PMN   $143,599,788.27
9         2014            PP   $448,950,874.62

In [182]:
df_pat.columns.tolist()

['ano_eleicao', 'sigla_partido', 'valor']